import Foundation

/// Result of parsing a DS Remote pairing QR code.
struct QRPairingPayload: Equatable {
    let version: Int
    let pairingCode: String
}

/// Strict parser for the DS Remote pairing QR URI.
///
/// Expected format (generated by the gateway):
///   dsremote://pair?v=1&code=472913
///
/// The scanner only ever acts on payloads produced by this parser; arbitrary
/// QR content is rejected.
enum QRPairingParser {
    static func parse(_ rawValue: String) throws -> QRPairingPayload {
        let trimmed = rawValue.trimmingCharacters(in: .whitespacesAndNewlines)
        guard let url = URLComponents(string: trimmed) else {
            throw AppError.notDSRemoteQR
        }
        guard url.scheme?.lowercased() == "dsremote" else {
            throw AppError.notDSRemoteQR
        }
        guard url.host?.lowercased() == "pair" else {
            throw AppError.notDSRemoteQR
        }
        let path = url.path
        guard path.isEmpty || path == "/" else {
            throw AppError.notDSRemoteQR
        }
        let items = url.queryItems ?? []
        var params: [String: String] = [:]
        for item in items {
            if let value = item.value {
                params[item.name] = value
            }
        }
        // Strict: exactly "v" and "code" are accepted in v1.
        guard params.count == 2, params["v"] == "1" else {
            throw AppError.notDSRemoteQR
        }
        guard let codeRaw = params["code"], let code = PairingCode.normalize(codeRaw) else {
            throw AppError.notDSRemoteQR
        }
        return QRPairingPayload(version: 1, pairingCode: code)
    }
}
